Support submit job to multle yarn clusters
- each cluster use its own HBOX_CONF_DIR
- tested yarn version: 2.6, 2.7, 3.2
- add test case for submitting a simple job

diff --git a/core/bin/hbox-submit b/core/bin/hbox-submit
--- a/core/bin/hbox-submit
+++ b/core/bin/hbox-submit
@@ -3,35 +3,25 @@
 set -euo pipefail
 [[ ${DEBUG-} != true ]] || set -x
 
-HBOX_HOME="$(cd -- "$(dirname -- "$0")"/.. && pwd)"
+[[ -d ${HBOX_HOME-} ]] || HBOX_HOME="$(cd -- "$(dirname -- "$0")"/.. && pwd)"
 
 # shellcheck source-path=SCRIPTDIR/..
-. "$HBOX_HOME/conf/hbox-env.sh"
+. "$HBOX_HOME/conf/hbox-common-env.sh" "$@"
+# hbox-common-env.sh setups required and optional environments:
+#   JAVACMD - required, path to java binary
+#   HBOX_CLASSPATH - required, classpath to run hbox
+#   HBOX_JAR - required, result array for finding the hbox main jars, may find 0 or multiple ones
+#   HBOX_CLIENT_OPTS - optional, java cli opts to pass to hbox client
 
-# Find the java binary
-if [[ ${JAVA_HOME-} ]] && [[ -x "${JAVA_HOME}/bin/java" ]]; then
-  RUNNER="${JAVA_HOME}/bin/java"
-elif hash java >/dev/null; then
-  RUNNER=java
-else
-  echo "[ERROR] JAVA_HOME is not set" >&2
+if (( ${#HBOX_JAR[@]} == 0 )); then
+  echo "[ERROR] Failed to find Hbox jar in $HBOX_HOME/lib." >&2
   exit 1
-fi
-
-HBOX_LIB_DIR="$HBOX_HOME/lib"
-
-num_jars="$(find "$HBOX_LIB_DIR" -maxdepth 1 -name "hbox*hadoop*.jar" | wc -l)"
-if (( num_jars == 0 )); then
-  echo "[ERROR] Failed to find Hbox jar in $HBOX_LIB_DIR." >&2
-  exit 1
-elif (( num_jars > 1 )); then
-  echo "[ERROR] Found multiple Hbox jars in $HBOX_LIB_DIR:" >&2
-  find "$HBOX_LIB_DIR" -maxdepth 1 -name "hbox*hadoop*.jar" >&2
+elif (( ${#HBOX_JAR[@]} > 1 )); then
+  echo "[ERROR] Found multiple Hbox jars in $HBOX_HOME/lib:" >&2
+  printf "  %s\n" "${HBOX_JAR[@]}"
   echo "Please remove all but one jar." >&2
   exit 1
 fi
 
-HBOX_JAR="$(find "$HBOX_LIB_DIR" -maxdepth 1 -name "hbox*hadoop*.jar")"
-
 # shellcheck disable=SC2086
-exec "$RUNNER" $CLIENT_EXTRA_JAVAOPTIONS -cp "$HBOX_CLASSPATH" org.apache.hadoop.util.RunJar "$HBOX_JAR" "$@"
+exec "$JAVACMD" ${HBOX_CLIENT_OPTS-} -cp "$HBOX_CLASSPATH" org.apache.hadoop.util.RunJar "${HBOX_JAR[0]}" "$@"
